### PR TITLE
feat: auth components

### PR DESCRIPTION
**Pull request by chungwwei**

### CODE REVIEW

**Comment by Leeoku** [comment]
This is OK for now, I'm sure we can find better ways to wrap things better, I think it's a bit clunky but can be optimized

**Comment by kevmo314** [comment]
> This is OK for now, I'm sure we can find better ways to wrap things better, I think it's a bit clunky but can be optimized. Also should use cloned repo after this PR, hard to peer review and test locally

You have to explicitly approve for review to allow the merge :)

**Comment by Leeoku** [comment]
hm maybe this is different from gitlab. if he pushes a new commit to fix my suggestion, then i'll have to reapprove. I guess we'll find out haha

**Comment by kevmo314** [comment]
> hm maybe this is different from gitlab. if he pushes a new commit to fix my suggestion, then i'll have to reapprove. I guess we'll find out haha

Yeah that's actually a setting that's disabled in this repo :D

**Pull request closed without merging**
